### ISSUE TITLE
How long does it take to train the model on CIFAR-10

### ISSUE THREAD

**Issue by forever208** [gnobitab/RectifiedFlow#12]
The default iteration is 1300k, which gonna take 5 days using a single A100...
Does the training really need 5 days?

**Comment by forever208** [comment]
@gnobitab Hi, it would be appreciated if you could share your training time on A100

**Comment by yuanzhi-zhu** [comment]
To the best of my knowledge, it takes ~3 days on a 3090 GPU

**Comment by forever208** [comment]
@yuanzhi-zhu thanks!
